name: complexnetworks
dependencies:
  - python=3.11.5
  - numpy=1.26.2
  - pandas=2.1.4  
  - jupyter=1.0.0
  - matplotlib=3.8.0
  - scikit-learn=1.2.2
  - statsmodels=0.14.0
  - pycairo=1.23.0
  - cython=3.0.6
  - seaborn=0.12.2
  - pip
  - pip:
    - igraph==0.11.3
    - powerlaw==1.5
    
